### ISSUE TITLE
Create an event sign-up page for International Nodeschool Day

### ISSUE THREAD

**Issue by awaterma** [nodeschool/bainbridge#2]
We need to create an event sign-up page for our May 23 event as described below:

https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md

**Comment by blakmatrix** [comment]
we got ours up, neighbors! feel free to steal that image http://www.meetup.com/Seattle-NodeSchool/events/221984469/

**Comment by awaterma** [comment]
Thanks Farrin!

**Comment by awaterma** [comment]
http://www.meetup.com/IslandJS-Nodeschool/events/222090027/
