### ISSUE TITLE
Nodeschool International Day Collaboration with Other Chapters

### ISSUE THREAD

**Issue by NorthDecoder** [nodeschool/bainbridge#7]
Nodeschool International Day on 21-May 2016 is an
ad hoc celebration of all things nodejs.  I thought
it would be a good idea for me to volunteer
as the timezone coordinator.

I am writing to see if Tacoma-JS can collaborate 
somehow that day via video chat and gitter with your
group for some part of the time from 0830-1200 PST
following the guidelines at [:link:](http://nodeschool.io/international-day).

I can be reached at:
  http://www.meetup.com/Tacoma-JS/events/226412924/
  https://github.com/NorthDecoder

**Comment by TylerMoeller** [comment]
Hello @NorthDecoder, thanks for reaching out to us. We definitely want to connect with another chapter during NodeSchool International Day, but ours is scheduled from 12:00-3:00 PM PST. Looks like we don't have any overlap, but if our schedule changes, I'll reply here to let you know. Please do the same! Thanks.
