### ISSUE TITLE
Nodeschool International Day 2016 -- Roll Call

### ISSUE THREAD

**Issue by awaterma** [nodeschool/bainbridge#8]
Hey @TylerMoeller, @flagoworld, here's the roll call I have from the event:

Andrew Waterman
Ryan Layne
Tyler Moeller
Bill Anderson
Michael Schneider

I guess we were all supposed to comment on an issue in our repository yesterday: https://github.com/nodeschool/international-day/issues/145

Could you guys kindly do so with a comment below? I'll see if Bill and Michael can help us out as well.

**Comment by TylerMoeller** [comment]
Thanks Andrew, I'll take care of it. 

@awaterma @flagoworld If you guys have pictures to share, can you send me a link? I'll upload those too for the 2016 video. 

Also, have either of you submitted feedback yet? If not, I'll take care of that too.
